### ISSUE TITLE
The pods do not startup If "wso2-server-volume" mount is empty.

### ISSUE THREAD

**Issue by sameerawickramasekara** [wso2/kubernetes-ei#123]
**Description:**

If we use an NFS mount for "wso2-server-volume" to add additional configs, and if it is empty at startup the pods will fail to start with a CrashLoopBackoff error. The error is thrown by the line [1]. if some content is added to the mount this error does not occur.

[1] - https://github.com/wso2/docker-ei/blob/3addbfc07fb97ddca6d5e525d7e7754013d7d461/dockerfiles/integrator/init.sh#L79

**Affected Product Version:**
wso2ei 6.3 official docker images

**Comment by chirangaalwis** [comment]
@sameerawickramasekara this has been fixed in the release of Docker and Docker Compose resources for WSO2 Enterprise Integrator [v6.5.0.2](https://github.com/wso2/docker-ei/releases/tag/v6.5.0.2).
