### ISSUE TITLE
ConfigMaps deletion commands need to be added to undeploy.sh

### ISSUE THREAD

**Issue by isuruirj** [wso2/kubernetes-ei#129]
**Description:**
ConfigMaps deletion commands need to be added to undeploy.sh

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
All the versions should get this improvement.

**Comment by chirangaalwis** [comment]
@isuruirj it is expected to promote Helm resources for WSO2 Integration deployment patterns as the primary and single source of Kubernetes resource installation. Hence, it has been suggested to deprecate the Kubernetes resources for WSO2 Integration deployment patterns in the future.
