### ISSUE TITLE
WSO2EI Simplified k8s resources does not deploy

### ISSUE THREAD

**Issue by NishikaDeSilva** [wso2/kubernetes-ei#166]
**Description:**
When running kubernetes simplified setup for WSO2 integrator with analytics, deployment "wso2ei-with-analytics-worker-deployment" keeps restarting. 

<img width="892" alt="Screen Shot 2019-07-04 at 11 29 19 AM" src="https://user-images.githubusercontent.com/47025945/60643381-7dffd000-9e50-11e9-8b74-f94c2381b91d.png">

Logs for the pod "wso2ei-with-analytics-worker-deployment-*"

<img width="1680" alt="Screen Shot 2019-07-04 at 11 23 40 AM" src="https://user-images.githubusercontent.com/47025945/60643416-9cfe6200-9e50-11e9-953a-383909eade32.png">

**Affected Product Version:** EI 6.5.0 

**OS, DB, other environment details and versions:**   MacOS High Sierra, minikube

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-ei/pull/167.
