### ISSUE TITLE
Introduce Elasticsearch for log aggregation and analysis for Kubernetes based WSO2 EI pattern deployments

### ISSUE THREAD

**Issue by Savidude** [wso2/kubernetes-ei#179]
**Description:**
Use Elasticsearch and Logstash for log aggregation and analysis in Helm Charts for WSO2 Enterprise Integrator deployment patterns.

**Affected Product Version:**
Helm resources for WSO2 Enterprise Integrator v6.5.x and below

**Comment by Aaquiff** [comment]
In the CI/CD setup we would have a single ELK(elasticsearch and Kibana only) stack. Each of the products being deployed will be having their own log-stash instance that would be pushing logs to this single elasticsearch instance each having a unique node name. This way it is possible to create indexes for each of these nodes and monitor these logs in Kibana.

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-ei/pull/206.
