### ISSUE TITLE
Formalize naming conventions for Helm resources

### ISSUE THREAD

**Issue by Savidude** [wso2/kubernetes-ei#183]
**Description:**
Names provided for deployment resources should be formalized following proper naming conventions. This would make the resources more organized. Additionally, this would resolve any conflicts that may occur if multiple deployment patterns were to be set up.

**Affected Product Version:**
 Helm resources for WSO2 Enterprise Integrator v6.5.x and below

**Comment by chirangaalwis** [comment]
Shall we go with the following naming pattern for Kubernetes resource definition names?

`wso2{product-name}-{pattern-name}-{profile-name}-{k8s-resource-name}`

For example, for the Integrator profile service in WSO2 Integration deployment pattern 1, this format would yield,

`wso2ei-pattern-1-integrator-service`

WDYT?

**Comment by Savidude** [comment]
+1 sounds good

**Comment by Aaquiff** [comment]
+1, Can we have {product-name}-{pattern-name}-{profile-name} this as a global variable to avoid duplicates.

**Comment by ThilinaManamgoda** [comment]
+1

**Comment by chirangaalwis** [comment]
+1 @Aaquiff for using the global variable.

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-ei/pull/194.
