### ISSUE TITLE
Analytics worker passive node is not ready

### ISSUE THREAD

**Issue by Aaquiff** [wso2/kubernetes-ei#197]
**Description:**
Currently analytics worker is in HA where on pod is passive and since the readiness probe is to the analytics port, the said pod is never ready. This is problematic when it comes to deployment tools such as spinnaker which waits for the pods to be ready after a deployment.

To avoid this, we will need to use two deployments of analytics worker fronted by a service each. The pods will be ready for each service since the readiness probe is set to the 9443 port. But only one service will serve traffic since we are using Failover configuration[1] of services in the integrator.

**Comment by Aaquiff** [comment]
Created #196 to fix this

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-ei/pull/196.
