### ISSUE TITLE
Add support for deploying artifacts across nodes

### ISSUE THREAD

**Issue by yhilem** [wso2/kubernetes-ei#23]
Hi,

Deploying artifacts across the nodes ( https://docs.wso2.com/display/EI611/Clustering+the+ESB+Profile#ClusteringtheESBProfile-Deployingartifactsacrossthenodes) is not implemented.

What happens when we scale WSO2 EI integrator profile into 
many number of container replicas ? (https://github.com/wso2/kubernetes-ei#6-how-to-scale-using-kubectl-scale)

For example, On Openshift, we can share an NFS mount (https://docs.openshift.com/enterprise/3.2/install_config/storage_examples/shared_storage.html).

Thanks,
Youcef HILEM

**Comment by DilanUA** [comment]
@yhilem ,

Thanks for noting down this and we are considering this requirement for an upcoming release for sure.
Currently, we are @ a prioritizing stage of these efforts according to the level of urgency required.

Best Regards,
Dilan.

**Comment by chirangaalwis** [comment]
@yhilem FYI, currently there is an effort being carried out on improving and fine tuning the [Kubernetes resources for WSO2 Enterprise Integrator](https://github.com/wso2/kubernetes-ei).

Please note that the aspects you have pointed out with regards to sharing artifacts across nodes in the cluster will be taken into account during this effort.
