### ISSUE TITLE
Create Helm charts for clustered Integrator profile

### ISSUE THREAD

**Issue by KavinduZoysa** [wso2/kubernetes-ei#78]
**Description:**
Helm charts should be created for the deployment of clustered Integrator profile.

**Suggested Labels:**
Type/Task

**Suggested Assignees:**

**Affected Product Version:**
WSO2 Enterprise Integrator v6.2.x

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-ei/pull/79.
