### ISSUE TITLE
Add Helm Charts for deployment pattens

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/kubernetes-ei#97]
**Description:**
Helm charts should be created for the deployment of Integrator & Broker with analytics.
Helm charts should be created for the deployment of Integrator with analytics.

**Suggested Labels:**
Type/NewFeature

**Affected Product Version:**
WSO2 Integrator  6.3.x

**Comment by chirangaalwis** [comment]
This is fixed in https://github.com/wso2/kubernetes-ei/pull/98.
